steps:
# Build the binary
- name: multiarch/crossbuild
  env:
  - CROSS_TRIPLE=arm-linux-gnueabi
  entrypoint: make
# Shove it into a container
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - t
  - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
  - -f
  - Dockerfile.cloudbuild
  - .

images:
- gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
