FROM resin/raspberrypi3-debian:stretch

RUN [ "cross-build-start" ]
RUN apt-get update && apt-get -y install --no-install-recommends \
autoconf \
automake \
build-essential \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

ADD . /app/
RUN [ "make" ]

RUN [ "cross-build-end" ]
RUN [ "cross-build-end" ]
RUN [ "cross-build-clean" ]

ENTRYPOINT ["/app/remserial"]
